table 'data (2)'
	lineageTag: 0abb5013-a441-4c92-9ea6-31e52063a23e

	measure 'Total Income' = SUM('data (2)'[Income])
		formatString: "₹"#,0.00;#,0.00\ -"₹";"₹"#,0.00
		lineageTag: 672bd4f8-0069-418e-947d-ea7f6e0df31a

		annotation PBI_FormatHint = {"currencyCulture":"hi-IN"}

	measure 'Total Expense' = SUMX('data (2)', 'data (2)'[Eating_Out] + 'data (2)'[Education] + 'data (2)'[Entertainment] + 'data (2)'[Groceries] + 'data (2)'[Healthcare] + 'data (2)'[Insurance] + 'data (2)'[Loan_Repayment] + 'data (2)'[Miscellaneous] + 'data (2)'[Rent] + 'data (2)'[Transport] + 'data (2)'[Utilities])
		formatString: "₹"#,0.00;#,0.00\ -"₹";"₹"#,0.00
		lineageTag: 1775f72f-5c13-47d1-876e-531fe167fc80

		annotation PBI_FormatHint = {"currencyCulture":"hi-IN"}

	measure 'Actual Savings' = [Total Income] - [Total Expense]
		formatString: "₹"#,0.00;#,0.00\ -"₹";"₹"#,0.00
		lineageTag: 5216d1cd-734e-40ae-9db1-c7396a59a770

		annotation PBI_FormatHint = {"currencyCulture":"hi-IN"}

	measure 'Desired Savings' = SUM('data (2)'[Desired_Savings])
		formatString: 0
		lineageTag: e88ca01f-5c8b-4149-9ca2-07e742fd8978

	measure 'Savings rate' = DIVIDE('data (2)'[Actual Savings], 'data (2)'[Total Income], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5712e847-fa0e-4c8c-bf94-5c243ed8ef4f

	measure 'Savings Variance' = [Actual Savings] - [Desired Savings]
		formatString: "₹"#,0.00;#,0.00\ -"₹";"₹"#,0.00
		lineageTag: 07210a38-e83a-40b9-abd9-52c3131d09c6

		annotation PBI_FormatHint = {"currencyCulture":"hi-IN"}

	measure 'Savings variance %' = DIVIDE([Savings Variance], [Desired Savings], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 42fdc8c0-daff-47a0-ade3-df8e6054dd8c

	column Income
		dataType: int64
		formatString: 0
		lineageTag: 957172ec-7292-4831-b6c0-b4158f05a2b1
		summarizeBy: sum
		sourceColumn: Income

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 0dfc290e-78bf-41b8-935a-69e287e5f69c
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Dependents
		dataType: int64
		formatString: 0
		lineageTag: a7607bb2-50df-46fb-80ce-92be0cef61b2
		summarizeBy: sum
		sourceColumn: Dependents

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: 9cd5d963-c3cb-496d-9a07-9f374af9ca30
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column City_Tier
		dataType: string
		lineageTag: 75616b3d-2c6f-4234-80b7-e36ec8ba883e
		summarizeBy: none
		sourceColumn: City_Tier

		annotation SummarizationSetBy = Automatic

	column Rent
		dataType: int64
		formatString: 0
		lineageTag: 8ebb6bed-d4ad-40c9-b16e-e0ed85dcaa95
		summarizeBy: sum
		sourceColumn: Rent

		annotation SummarizationSetBy = Automatic

	column Loan_Repayment
		dataType: int64
		formatString: 0
		lineageTag: 5879ffc6-0ea8-4119-9db2-b8fff2f6f1c0
		summarizeBy: sum
		sourceColumn: Loan_Repayment

		annotation SummarizationSetBy = Automatic

	column Insurance
		dataType: int64
		formatString: 0
		lineageTag: aae387e8-b6ef-4aa8-9c5c-5376267e3a3d
		summarizeBy: sum
		sourceColumn: Insurance

		annotation SummarizationSetBy = Automatic

	column Groceries
		dataType: int64
		formatString: 0
		lineageTag: 39ed503c-d48e-4837-8b9f-20bef3121b1c
		summarizeBy: sum
		sourceColumn: Groceries

		annotation SummarizationSetBy = Automatic

	column Transport
		dataType: int64
		formatString: 0
		lineageTag: f779c6dd-012a-4a8e-ab6f-12c53017f840
		summarizeBy: sum
		sourceColumn: Transport

		annotation SummarizationSetBy = Automatic

	column Eating_Out
		dataType: int64
		formatString: 0
		lineageTag: eaa5c706-79dc-4eba-94e6-e52b512729cb
		summarizeBy: sum
		sourceColumn: Eating_Out

		annotation SummarizationSetBy = Automatic

	column Entertainment
		dataType: int64
		formatString: 0
		lineageTag: 9ec5b05a-97e9-46c6-8c1a-56ed7b203873
		summarizeBy: sum
		sourceColumn: Entertainment

		annotation SummarizationSetBy = Automatic

	column Utilities
		dataType: int64
		formatString: 0
		lineageTag: b6e490e8-4cb8-40bc-933b-63adece31f46
		summarizeBy: sum
		sourceColumn: Utilities

		annotation SummarizationSetBy = Automatic

	column Healthcare
		dataType: int64
		formatString: 0
		lineageTag: cbf5ecdb-4372-4726-bfcb-850d5e748fee
		summarizeBy: sum
		sourceColumn: Healthcare

		annotation SummarizationSetBy = Automatic

	column Education
		dataType: int64
		formatString: 0
		lineageTag: 9e8b3a13-cff3-455f-b716-dbac06ca4cad
		summarizeBy: sum
		sourceColumn: Education

		annotation SummarizationSetBy = Automatic

	column Miscellaneous
		dataType: int64
		formatString: 0
		lineageTag: 6e5be5de-ad7e-4e39-a0af-4f111af8f641
		summarizeBy: sum
		sourceColumn: Miscellaneous

		annotation SummarizationSetBy = Automatic

	column Desired_Savings_Percentage
		dataType: int64
		formatString: 0
		lineageTag: 2078b91b-e9b0-4447-8038-52025bddbf26
		summarizeBy: sum
		sourceColumn: Desired_Savings_Percentage

		annotation SummarizationSetBy = Automatic

	column Desired_Savings
		dataType: int64
		formatString: 0
		lineageTag: e517799a-9d9a-447e-98a9-d407f2af761c
		summarizeBy: sum
		sourceColumn: Desired_Savings

		annotation SummarizationSetBy = Automatic

	column Disposable_Income
		dataType: int64
		formatString: 0
		lineageTag: 3128ec87-806f-4c92-8dd2-1a1e0aa42d99
		summarizeBy: sum
		sourceColumn: Disposable_Income

		annotation SummarizationSetBy = Automatic

	column Potential_Savings_Groceries
		dataType: int64
		formatString: 0
		lineageTag: 4277d695-1935-4f7f-b6f3-d3ff4c761959
		summarizeBy: sum
		sourceColumn: Potential_Savings_Groceries

		annotation SummarizationSetBy = Automatic

	column Potential_Savings_Transport
		dataType: int64
		formatString: 0
		lineageTag: 5f7a8b65-cc66-4eca-ba22-bce807f717fe
		summarizeBy: sum
		sourceColumn: Potential_Savings_Transport

		annotation SummarizationSetBy = Automatic

	column Potential_Savings_Eating_Out
		dataType: int64
		formatString: 0
		lineageTag: b60b56b1-c317-4043-8c57-598081740c6f
		summarizeBy: sum
		sourceColumn: Potential_Savings_Eating_Out

		annotation SummarizationSetBy = Automatic

	column Potential_Savings_Entertainment
		dataType: int64
		formatString: 0
		lineageTag: 0d89e48c-d2ce-426e-96c8-d9d1b2817d84
		summarizeBy: sum
		sourceColumn: Potential_Savings_Entertainment

		annotation SummarizationSetBy = Automatic

	column Potential_Savings_Utilities
		dataType: int64
		formatString: 0
		lineageTag: 57e62ffe-6cd0-4a18-990b-fcd492585fb8
		summarizeBy: sum
		sourceColumn: Potential_Savings_Utilities

		annotation SummarizationSetBy = Automatic

	column Potential_Savings_Healthcare
		dataType: int64
		formatString: 0
		lineageTag: 2722af3b-578b-47da-bae2-e72dba22edff
		summarizeBy: sum
		sourceColumn: Potential_Savings_Healthcare

		annotation SummarizationSetBy = Automatic

	column Potential_Savings_Education
		dataType: int64
		formatString: 0
		lineageTag: cb6cb65a-0ca4-4c95-8dea-bc5c71dbaa96
		summarizeBy: sum
		sourceColumn: Potential_Savings_Education

		annotation SummarizationSetBy = Automatic

	column Potential_Savings_Miscellaneous
		dataType: int64
		formatString: 0
		lineageTag: 191886f4-64b4-462d-b719-533fac28c1d5
		summarizeBy: sum
		sourceColumn: Potential_Savings_Miscellaneous

		annotation SummarizationSetBy = Automatic

	column 'Income Bracket'
		dataType: string
		lineageTag: b7453def-8d12-40e6-b2b5-845ef128e4f9
		summarizeBy: none
		sourceColumn: Income Bracket

		annotation SummarizationSetBy = Automatic

	column 'Age Range'
		dataType: string
		lineageTag: 596ffddb-9304-455c-92c8-5550f9b51232
		summarizeBy: none
		sourceColumn: Age Range

		annotation SummarizationSetBy = Automatic

	partition 'data (2)' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\MY PC\Pictures\archive(1)\data.csv"),[Delimiter=",", Columns=27, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Income", Int64.Type}, {"Age", Int64.Type}, {"Dependents", Int64.Type}, {"Occupation", type text}, {"City_Tier", type text}, {"Rent", Int64.Type}, {"Loan_Repayment", Int64.Type}, {"Insurance", Int64.Type}, {"Groceries", Int64.Type}, {"Transport", Int64.Type}, {"Eating_Out", Int64.Type}, {"Entertainment", Int64.Type}, {"Utilities", Int64.Type}, {"Healthcare", Int64.Type}, {"Education", Int64.Type}, {"Miscellaneous", Int64.Type}, {"Desired_Savings_Percentage", Int64.Type}, {"Desired_Savings", Int64.Type}, {"Disposable_Income", Int64.Type}, {"Potential_Savings_Groceries", Int64.Type}, {"Potential_Savings_Transport", Int64.Type}, {"Potential_Savings_Eating_Out", Int64.Type}, {"Potential_Savings_Entertainment", Int64.Type}, {"Potential_Savings_Utilities", Int64.Type}, {"Potential_Savings_Healthcare", Int64.Type}, {"Potential_Savings_Education", Int64.Type}, {"Potential_Savings_Miscellaneous", Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "Income Bracket", each if [Income] <= 20000 then "Low" else if [Income] <= 50000 then "Middle" else "High"),
				    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "Age Range", each if [Age] <= 20 then "10-20" else if [Age] <= 35 then "21-35" else if [Age] <= 50 then "36-50" else "Greater than 50")
				in
				    #"Added Conditional Column1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

