table Articles
	lineageTag: e9601ea3-1ad8-4abe-8555-a2844dbfa28d

	column Name
		dataType: string
		lineageTag: 24fa96d9-a443-45fe-ba80-7dbf1bcd9985
		summarizeBy: none
		sourceColumn: Name
		sortByColumn: id

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Link
		dataType: string
		lineageTag: 77ddd265-6aaa-48ba-a886-ef0339a36502
		summarizeBy: none
		sourceColumn: Link

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		lineageTag: 6bc64765-18d1-4874-9e9a-248acc99e5c7
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	partition Articles-b9405de1-00ce-4514-8cf9-77bc9119df05 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\! Dasha\LinkedIn проекты\Interactive Resume\CVexcel.xlsx"), null, true),
				    Articles_Sheet = Source{[Item="Articles",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Articles_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Name", type text}, {"Link", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

