table Certification
	lineageTag: 6dab2b2d-baa6-4779-a9b8-fc0a33c7ffad

	column Date
		dataType: dateTime
		formatString: mmm yyyy
		lineageTag: a0140125-fc30-456d-b347-2f76f0cc1c07
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column Certification
		dataType: string
		lineageTag: 370c1850-3651-4fdd-9f17-9ffca05d4e9d
		summarizeBy: none
		sourceColumn: Certification

		annotation SummarizationSetBy = Automatic

	column Details
		dataType: string
		lineageTag: 3439748a-0b36-4268-8709-9b2c5fc83f83
		summarizeBy: none
		sourceColumn: Details

		annotation SummarizationSetBy = Automatic

	column 'Main Tool'
		dataType: string
		lineageTag: 978e691d-f817-4e4f-be40-27dc664ee4a2
		summarizeBy: none
		sourceColumn: Main Tool

		annotation SummarizationSetBy = Automatic

	partition Certification-0f2a5cb2-4b25-40bb-8bca-697177d3fe68 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\! Dasha\LinkedIn проекты\Interactive Resume\CVexcel.xlsx"), null, true),
				    Certification_Sheet = Source{[Item="Certification",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Certification_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Certification", type text}, {"Details", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

