table Companies
	lineageTag: 75bdf595-3299-4351-b945-5abbed81285e

	column Company
		dataType: string
		lineageTag: ff149b32-c15a-4c77-9dc0-f06439a4b4c3
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Logo
		dataType: string
		lineageTag: 1d23ca2f-831e-48a8-b05d-fc0ebe98b655
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Logo

		annotation SummarizationSetBy = Automatic

	column 'Company link'
		dataType: string
		lineageTag: f37434e5-4772-4301-a163-f83fcac86d50
		summarizeBy: none
		sourceColumn: Company link

		annotation SummarizationSetBy = Automatic

	column 'Year start'
		dataType: dateTime
		formatString: mmm yyyy
		lineageTag: 9d11b570-5838-4d5a-8dbf-9fcee1122156
		summarizeBy: none
		sourceColumn: Year start

		variation Variation
			isDefault
			relationship: 9a2eb4db-92ce-4dca-9908-fa42e8d299b2
			defaultHierarchy: LocalDateTable_4ecd85e8-749d-4a28-a0c2-e1c5c46fd6fa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	partition Companies-80a9bab5-703f-411f-b916-7f146fedee2d = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\! Dasha\LinkedIn проекты\Interactive Resume\CVexcel.xlsx"), null, true),
				    Companies_Sheet = Source{[Item="Companies",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Companies_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Company", type text}, {"Logo", type text}, {"Company link", type text}, {"Year start", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

