table Education
	lineageTag: 0bbaa584-2fe4-4431-ab21-adecf2f89f83

	column Education
		dataType: string
		lineageTag: fd556468-09c7-4d0b-9d62-bc6319a02f65
		summarizeBy: none
		sourceColumn: Education

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 943f48e3-08dc-46ea-9ec4-98ef6371ed23
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Main education'
		dataType: string
		lineageTag: 51fcfef7-ffb3-4e31-a589-58fd7e0e64d6
		summarizeBy: none
		sourceColumn: Main education

		annotation SummarizationSetBy = Automatic

	column 'Main Tool'
		dataType: string
		lineageTag: dea7add3-b9cb-494f-8c60-a29a1ab1d927
		summarizeBy: none
		sourceColumn: Main Tool

		annotation SummarizationSetBy = Automatic

	partition Education-df856f05-c719-46fb-a9d5-4f48ec29c331 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\! Dasha\LinkedIn проекты\Interactive Resume\CVexcel.xlsx"), null, true),
				    Education_Sheet = Source{[Item="Education",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Education_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Education", type text}, {"Year", Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "Custom", each if [Education] = "Training courses “Digital marketing” and “Internet marketing”, Minsk, ARTOX media" then "Training courses" else if [Education] = "Training course “IBM Cognos 10 BI”, Minsk, IBA" then "Training courses" else if [Education] = "Training course “Basics of IBM SPSS Modeler”, Minsk, IBA" then "Training courses" else if [Education] = "Tableau Web-Based Training “Tableau eLearning”. Certificates: “Desktop I: Fundamentals”, “Desktop II: Intermediate”, “Desktop III: Advanced”, “Tableau Services & Support” and other. Badges: ""Tableau Analyst"", ""Tableau Designer"" ,""Tableau Author"", ""Tableau Consumer""" then "Training courses" else if [Education] = "Online course “70-778, DA-100: Analyzing and Visualizing Data with Power BI”. The “Certificate of completion“ was received, Udemy" then "Training courses" else if [Education] = "Tableau Web-Based Training “Tableau eLearning”. Certificates and Badges: “Manage and Maintain Tableau Server”, “Manage and Maintain Tableau Sites”, “Plan and Build Tableau Server Deployments”" then "Training courses" else if [Education] = "Online course “Guide to Dashboards using IBM Cognos Analytics“. The “Certificate of completion“ was received, Udemy" then "Training courses" else if [Education] = "Online course “SQL - The Complete Developer's Guide (MySQL, PostgreSQL)“. The “Certificate of completion“ was received, Udemy" then "Training courses" else if [Education] = "English courses, Institute of IT & Business Administration, Minsk" then "Language courses" else if [Education] = "Polish courses, Institute of IT & Business Administration, Minsk" then "Language courses" else if [Education] = "English courses, EffectiveSoft, Minsk" then "Language courses" else if [Education] = "Belarusian State University, Faculty of Mathematics and Mechanics, Mathematical methods in economics" then "Belarusian State University" else [Education], type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Conditional Column",{{"Custom", "Main education"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

