table 'Experience (2)'
	lineageTag: ed5a8e57-5c0a-4ebc-97c2-2245de816090

	column 'Project Name'
		dataType: string
		lineageTag: dd5dd47e-3b09-4780-80bb-af21385bf61e
		summarizeBy: none
		sourceColumn: Project Name

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: 83ee4037-b535-447b-a157-7dd144feda5d
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Experience (2)-175e8268-567a-404c-88be-ad4b309d7997' = m
		mode: import
		source =
				let
				    Source = Experience,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Project Name", "Technologies and Tools"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Other Columns", "Technologies and Tools", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"Technologies and Tools.1", "Technologies and Tools.2", "Technologies and Tools.3", "Technologies and Tools.4", "Technologies and Tools.5", "Technologies and Tools.6", "Technologies and Tools.7", "Technologies and Tools.8"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Technologies and Tools.1", type text}, {"Technologies and Tools.2", type text}, {"Technologies and Tools.3", type text}, {"Technologies and Tools.4", type text}, {"Technologies and Tools.5", type text}, {"Technologies and Tools.6", type text}, {"Technologies and Tools.7", type text}, {"Technologies and Tools.8", type text}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"Project Name"}, "Attribute", "Value"),
				    #"Removed Columns" = Table.RemoveColumns(#"Unpivoted Columns",{"Attribute"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

