table Languages
	lineageTag: ce8da3e6-ce73-41f2-9b2f-d980283cfb10

	column Language
		dataType: string
		lineageTag: 9a85e319-ccec-47df-98d5-dd67b136c8bb
		summarizeBy: none
		sourceColumn: Language

		annotation SummarizationSetBy = Automatic

	column Level
		dataType: string
		lineageTag: 191c540d-88e7-4018-96cf-f1f684e1c2e8
		summarizeBy: none
		sourceColumn: Level

		annotation SummarizationSetBy = Automatic

	partition Languages-c9190884-96a0-40b7-8a50-4f36a0b7a5da = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\! Dasha\LinkedIn проекты\Interactive Resume\CVexcel.xlsx"), null, true),
				    Languages_Sheet = Source{[Item="Languages",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Languages_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Language", type text}, {"Level", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

