table Technology
	lineageTag: 3ef00ebc-8fd6-469c-874c-5fecb80974a1

	measure BI_Expert_years = YEAR(TODAY()) - 2014
		formatString: 0
		lineageTag: 743e4dc8-426e-41ea-b504-aac6ba09b624

	column Technology
		dataType: string
		lineageTag: 4d5d10ac-85f5-485b-aa03-11d9c896bc64
		summarizeBy: none
		sourceColumn: Technology

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 4e28c2b2-957c-48ff-ad4f-cdcb23ca21b8
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Years
		dataType: int64
		formatString: 0
		lineageTag: 8234256d-9aff-425d-ad17-860635595515
		summarizeBy: sum
		sourceColumn: Years

		annotation SummarizationSetBy = Automatic

	column 'From date'
		dataType: int64
		formatString: 0
		lineageTag: 8772c6d7-8147-4bb1-9d84-c487b3d8a8aa
		summarizeBy: sum
		sourceColumn: From date

		annotation SummarizationSetBy = Automatic

	partition Technology-c2ee0f4b-fd27-4d75-a775-5efd1a0aaad8 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\! Dasha\LinkedIn проекты\Interactive Resume\CVexcel.xlsx"), null, true),
				    Technology_Sheet = Source{[Item="Technology",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Technology_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Technology", type text}, {"Category", type text}, {"Years", Int64.Type}, {"From date", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

